# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='state_of_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('ACTIVE', 'активен'), ('DELETED', 'удалён')], default='ACTIVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='state_of_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('HAVE_ACTIVE_QUESTS', 'есть активные квесты'), ('HAVE_NO_ACTIVE_QUESTS', 'нет активных квестов'), ('DELETED', 'удалена')], default='HAVE_NO_ACTIVE_QUESTS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='state_of_team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('ACTIVE', 'активен'), ('DOES_NOT_RECIEVE_NOTES', 'не получает уведомления'), ('DELETED_FROM_TEAM', 'удалён из команды'), ('TEAM_DELETED', 'команда удалена')], default='ACTIVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.member')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.state_of_team')),
            ],
        ),
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.member')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.state_of_team_member')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.team')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.state_of_member'),
        ),
    ]
