# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questForBandsBotDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id_state',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id_captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id_state',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='id_member',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='id_state',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='id_team',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='state_of_member',
        ),
        migrations.DeleteModel(
            name='state_of_team',
        ),
        migrations.DeleteModel(
            name='state_of_team_member',
        ),
        migrations.DeleteModel(
            name='team',
        ),
        migrations.DeleteModel(
            name='team_member',
        ),
    ]
