# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questForBandsBotDB', '0005_auto_20171201_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_state',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.state_of_member'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='id_state',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='questForBandsBotDB.state_of_team_member'),
        ),
    ]
