# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questForBandsBotDB', '0008_auto_20171201_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_of_team',
            name='descript',
            field=models.CharField(choices=[('HAVE_ACTIVE_QUESTS', 'есть активные квесты'), ('HAVE_NO_ACTIVE_QUESTS', 'нет активных квестов'), ('DELETED', 'удалена')], default='HAVE_NO_ACTIVE_QUESTS', max_length=50, unique=True),
        ),
    ]
