# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questForBandsBotDB', '0010_auto_20171201_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram_user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
