# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questForBandsBotDB', '0012_auto_20171201_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
